version: '2'

services:
  flask:
    image: flasky
    ports:
      - "9001:9001"  # Port Flask is running on
    restart: always

  reverseproxy:
    image: fnginx
    ports:
      - 8080:8080 # Port NGINX is listening on 


    restart: always

