version: '3.3'

services:
  db:
    build: .
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'my-secret-pw'
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypassword'
    ports:
      - '9000:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
